stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Сборка Docker-образа..."
    - docker build -t avtopartner-landing .
    - docker images

test_job:
  stage: test
  script:
    - echo "Запуск контейнера..."
    - docker run -d --name test-container -p 8080:80 avtopartner-landing
    - timeout /t 3 /nobreak >nul
    - curl.exe -f http://localhost:8080
    - docker stop test-container
    - docker rm test-container